version: 2
updates:
  # JavaScript/TypeScript dependencies (root)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
      - security
    reviewers:
      - acailic
    assignees:
      - acailic
    versioning-strategy: increase
    commit-message:
      prefix: build
      include: scope
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    security-updates-only: true
    ignore:
      # Major updates for frameworks or tools that may require manual review
      - dependency-name: "@tauri-apps/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "playwright"
        update-types:
          - "version-update:semver-major"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "04:00"
    labels:
      - dependencies
      - ci
    reviewers:
      - acailic
    assignees:
      - acailic
    commit-message:
      prefix: ci

  # Rust/Cargo dependencies (Tauri)
  - package-ecosystem: cargo
    directory: "/src-tauri"
    schedule:
      interval: weekly
      day: sunday
      time: "04:15"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust
      - tauri
    reviewers:
      - acailic
    assignees:
      - acailic
    versioning-strategy: increase
    commit-message:
      prefix: build
      include: scope
    ignore:
      - dependency-name: "tauri"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "wry"
        update-types:
          - "version-update:semver-major"

