# Funding Options for ArchiComm
# These are supported funding model platforms

github: [acailic]
patreon: # Add Patreon username here when available
open_collective: # Add Open Collective username here when available
ko_fi: # Add Ko-fi username here when available
tidelift: # Add Tidelift package name here when available
community_bridge: # Add Community Bridge project name here when available
liberapay: # Add Liberapay username here when available
issuehunt: # Add IssueHunt username here when available
lfx_crowdfunding: # Add LFX Crowdfunding project name here when available
polar: # Add Polar username here when available
buy_me_a_coffee: # Add Buy Me a Coffee username here when available
thanks_dev: # Add thanks.dev username here when available
custom: # Add custom sponsorship URLs here when available