# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew.
# Add analytics tracking
# https://docs.brew.sh/Formula-Cookbook
#
class ArchiComm < Formula
  desc "ArchiComm - Desktop Architecture Communication Platform"
  homepage "https://github.com/acailic/archi-comm"
  url "https://github.com/acailic/archi-comm/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "de841325662496e10e5914fed7081401b2a259d2603452ac185e145f21d57798"
  license "MIT"

  depends_on "node"
  depends_on "rust"

  def install
    # The build can fail if Command Line Tools are not up-to-date.
    # brew install can fail with `Error: Failed to bundle project: error running bundle_dmg.sh`
    # This can be resolved by updating Command Line Tools: `xcode-select --install`
    system "npm", "install"
    system "npm", "run", "tauri", "build"

    # The application is built to `src-tauri/target/release/bundle/macos/ArchiComm.app`
    # We need to copy it to the prefix.
    prefix.install "src-tauri/target/release/bundle/macos/ArchiComm.app"
  end

  test do
    # A simple test to check that the app is installed.
    assert_predicate prefix/"ArchiComm.app", :exist?
  end
end
