// Auto-generated UI components barrel. Edit the generation script if structure changes.
export * from './accessibility/AccessibilityProvider';
export * from './DesignCanvas';
export * from './diagnostics';
export * from './figma';
export * from './icons';
export * from './shortcuts';
export * from './ui';
export * from './pages/AIConfigPage';
export * from './modals/AnnotationEditDialog';
export * from './AppContainer';
export { default as AppContainer } from './AppContainer';
export * from './AssessmentPanel';
export * from './AssignmentPanel';
export * from './AudioRecording';
export * from './overlays/CanvasAnnotationOverlay';
export * from './canvas/CanvasArea';
export * from './canvas/CanvasComponent';
export { default as CanvasComponent } from './canvas/CanvasComponent';
export * from './ChallengeManager';
export * from './ChallengeSelection';
export * from './CommandPalette';
export * from './panels/ComponentPalette';
export * from './Confetti';
export { default as Confetti } from './Confetti';
export * from './pages/ConfigPage';
export * from './ContextualHelpSystem';
export { default as ContextualHelpSystem } from './ContextualHelpSystem';
export * from './overlays/DevOverlay';
export { default as DevOverlay } from './overlays/DevOverlay';
export * from './pages/DeveloperDiagnosticsPage';
export { default as DeveloperDiagnosticsPage } from './pages/DeveloperDiagnosticsPage';
export * from './ImportExportDropdown';
export * from './modals/ImportExportModal';
export * from './LazyComponentWrapper';
export { default as LazyComponentWrapper } from './LazyComponentWrapper';
export * from './LearningBreadcrumbs';
export { default as LearningBreadcrumbs } from './LearningBreadcrumbs';
export * from './panels/LeetCodeStylePanel';
export * from './canvas/Minimap';
export * from './overlays/OnboardingOverlay';
export { default as OnboardingOverlay } from './overlays/OnboardingOverlay';
export * from './pages/ProVersionPage';
export { default as ProVersionPage } from './pages/ProVersionPage';
export * from './PropertiesPanel';
export * from './overlays/RecoveryOverlay';
export { default as RecoveryOverlay } from './overlays/RecoveryOverlay';
export * from './pages/ReviewScreen';
export * from './layout/RightSidebar';
export * from './layout/Router';
export { default as Router } from './layout/Router';
export * from './panels/ShortcutCustomizationPanel';
export { default as ShortcutCustomizationPanel } from './panels/ShortcutCustomizationPanel';
export * from './SolutionHints';
export * from './SolutionValidationCard';
export * from './layout/StatusBar';
export * from './TauriDemo';
export * from './layout/TopBar';
export { default as TopBar } from './layout/TopBar';
export * from './TranscriptEditor';
export * from './UXRecommendationToast';
export { default as UXRecommendationToast } from './UXRecommendationToast';
export * from './layout/VerticalSidebar';
export * from './overlays/WelcomeOverlay';
export * from './panels/WhatIfPanel';
export { default as WhatIfPanel } from './panels/WhatIfPanel';
export * from './layout/WindowControls';
export * from './icon-registry';
