// Auto-generated UI components barrel. Edit the generation script if structure changes.
export * from './DesignCanvas';
export * from './diagnostics';
export * from './figma';
export * from './icons';
export * from './shortcuts';
export * from './ui';
export * from './AIConfigPage';
export * from './AnnotationEditDialog';
export * from './AppContainer';
export { default as AppContainer } from './AppContainer';
export * from './AssessmentPanel';
export * from './AssignmentPanel';
export * from './AudioRecording';
export * from './CanvasAnnotationOverlay';
export * from './CanvasArea';
export * from './CanvasComponent';
export { default as CanvasComponent } from './CanvasComponent';
export * from './ChallengeManager';
export * from './ChallengeSelection';
export * from './CommandPalette';
export * from './ComponentPalette';
export * from './Confetti';
export { default as Confetti } from './Confetti';
export * from './ConfigPage';
export * from './ContextualHelpSystem';
export { default as ContextualHelpSystem } from './ContextualHelpSystem';
export * from './DevOverlay';
export { default as DevOverlay } from './DevOverlay';
export * from './DeveloperDiagnosticsPage';
export { default as DeveloperDiagnosticsPage } from './DeveloperDiagnosticsPage';
export * from './ImportExportDropdown';
export * from './ImportExportModal';
export * from './LazyComponentWrapper';
export { default as LazyComponentWrapper } from './LazyComponentWrapper';
export * from './LearningBreadcrumbs';
export { default as LearningBreadcrumbs } from './LearningBreadcrumbs';
export * from './LeetCodeStylePanel';
export * from './Minimap';
export * from './OnboardingOverlay';
export { default as OnboardingOverlay } from './OnboardingOverlay';
export * from './PerformanceDashboard';
export * from './ProVersionPage';
export { default as ProVersionPage } from './ProVersionPage';
export * from './PropertiesPanel';
export * from './RecoveryOverlay';
export { default as RecoveryOverlay } from './RecoveryOverlay';
export * from './ReviewScreen';
export * from './RightSidebar';
export * from './Router';
export { default as Router } from './Router';
export * from './ShortcutCustomizationPanel';
export { default as ShortcutCustomizationPanel } from './ShortcutCustomizationPanel';
export * from './SolutionHints';
export * from './SolutionValidationCard';
export * from './StatusBar';
export * from './TauriDemo';
export * from './TopBar';
export { default as TopBar } from './TopBar';
export * from './TranscriptEditor';
export * from './UXRecommendationToast';
export { default as UXRecommendationToast } from './UXRecommendationToast';
export * from './VerticalSidebar';
export * from './WelcomeOverlay';
export * from './WhatIfPanel';
export { default as WhatIfPanel } from './WhatIfPanel';
export * from './WindowControls';
export * from './icon-registry';
