name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    name: Lint, Format, Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Cache Vite/Vitest
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vite
            .vite
          key: vite-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            vite-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Verify TypeScript type packages
        run: npm run verify:types

      - name: Type check
        run: npm run type-check

      - name: Prettier check
        run: npm run format:check

      - name: ESLint
        run: npm run lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [ lint-and-typecheck ]
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Cache Vite/Vitest
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vite
            .vite
          key: vite-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            vite-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:run

  web-build:
    name: Web Production Build
    runs-on: ubuntu-latest
    needs: [ lint-and-typecheck ]
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Cache Vite/Vitest
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vite
            .vite
          key: vite-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            vite-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build web (vite)
        run: npm run web:build
