name: Update Homebrew Cask

on:
  workflow_run:
    workflows: ["Build Tauri App"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-cask:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get latest release info
        id: release
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/acailic/archi-comm/releases/latest | jq -r .tag_name)
          version=${latest_tag#v}
          echo "version=${version}" >> $GITHUB_OUTPUT
          dmg_url="https://github.com/acailic/archi-comm/releases/download/${latest_tag}/ArchiComm_${version}_universal.dmg"
          sha=$(curl -sL "${dmg_url}" | shasum -a 256 | cut -d ' ' -f 1)
          echo "sha256=${sha}" >> $GITHUB_OUTPUT

      - name: Update cask version and checksum
        env:
          VERSION: ${{ steps.release.outputs.version }}
          SHA256: ${{ steps.release.outputs.sha256 }}
        run: |
          sed -i '' \
            -e "s/version \".*\"/version \"${VERSION}\"/" \
            -e "s/sha256 :no_check/sha256 \"${SHA256}\"/" \
            Casks/archi-comm.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "feat: update Homebrew cask to version ${{ steps.release.outputs.version }}"
          title: "Update Homebrew cask to version ${{ steps.release.outputs.version }}"
          body: |
            Updates the ArchiComm Homebrew cask to version ${{ steps.release.outputs.version }}.
            - Updates version number
            - Updates SHA256 checksum
            
            This PR was automatically generated by the Update Homebrew Cask workflow.
          branch: "update-cask-v${{ steps.release.outputs.version }}"
          delete-branch: true