name: Automated Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run semantic-release in dry-run mode"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      actions: write
    steps:
      - name: Checkout
      	uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release (dry-run)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:dry

      - name: Release
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.dry-run != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

      - name: Note
        if: always()
        run: |
          echo "If a new version was released, the created tag will trigger the Tauri build workflow to produce platform-specific artifacts."

